---
- name: Common tool setup on all the servers
  hosts: appsrvgrp
  become: yes
  vars:
    tom_url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.1.28/bin/apache-tomcat-10.1.28.tar.gz

  tasks:
    - name: Install JDK 17 on CentOS
      yum:
        name: java-17-openjdk
        state: present
      when: ansible_distribution == 'CentOS'

    - name: Install JDK 17 on Ubuntu
      apt:
        name: openjdk-17-jdk
        state: present
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'

    - name: Download Tomcat 10 Tar Ball/Binaries
      get_url:
        url: "{{tom_url}}"
        dest: /tmp/tomcat-10.tar.gz

    - name: Add tomcat group
      group:
        name: tomcat
        state: present

    - name: Add tomcat user
      user:
        name: tomcat
        group: tomcat
        shell: /bin/nologin
        home: /usr/local/tomcat10

    - name: Create /usr/local/tomcat10 directory
      file:
        path: /usr/local/tomcat10
        state: directory
        owner: tomcat
        group: tomcat
        mode: '0755'

    - name: Extract Tomcat 10 directly into /usr/local/tomcat10
      unarchive:
        src: /tmp/tomcat-10.tar.gz
        dest: /usr/local/tomcat10/
        remote_src: yes
        extra_opts:
          - --strip-components=1
        owner: tomcat
        group: tomcat

    - name: Ensure tomcat bin scripts are executable
      file:
        path: /usr/local/tomcat10/bin
        mode: "a+x"
        recurse: yes

    - name: Setup tomcat systemd service file on Ubuntu
      template:
        src: templates/ubuntu16-svcfile.j2
        dest: /etc/systemd/system/tomcat.service
        mode: "0644"
      when: ansible_distribution == 'Ubuntu'

    - name: Force systemd to reread configs
      systemd:
        daemon_reload: yes

    - name: Start & Enable Tomcat 10
      service:
        name: tomcat
        state: started
        enabled: yes
