pipeline {
    agent any

    options {
        timestamps() // Adds timestamps to every console log line
    }

    tools {
        maven "MAVEN3"
        jdk "JDK17"
    }

    environment {
        NEXUS_VERSION       = "nexus3"
        NEXUS_PROTOCOL      = "http"
        NEXUS_URL           = "100.58.201.192:8081"
        NEXUS_REPOSITORY    = "vprofile-release"
        NEXUS_REPO_ID       = "vprofile-release"
        NEXUS_CREDENTIAL_ID = "nexuslogin"
        MAVEN_OPTS          = "-Xms256m -Xmx1024m"
    }

    stages {
        stage('BUILD') {
            steps {
                // Switch into v_project folder where pom.xml is located
                dir('v_project') {
                    sh 'mvn clean install -DskipTests'
                }
            }
            post {
                success {
                    echo 'Now Archiving...'
                    archiveArtifacts artifacts: '**/target/*.war'
                }
            }
        }

        stage('UNIT TEST') {
            steps {
                dir('v_project') {
                    sh 'mvn test'
                }
            }
        }

        stage('INTEGRATION TEST') {
            steps {
                dir('v_project') {
                    sh 'mvn verify -DskipUnitTests'
                }
            }
        }

        stage('CODE ANALYSIS WITH CHECKSTYLE') {
            steps {
                dir('v_project') {
                    sh 'mvn checkstyle:checkstyle'
                }
            }
            post {
                success {
                    echo 'Generated Analysis Result'
                }
            }
        }

        stage('CODE ANALYSIS with SONARQUBE') {
            environment {
                scannerHome = tool 'sonarscanner4'
            }
            steps {
                dir('v_project') {
                    withSonarQubeEnv('sonar-pro') {
                        sh '''${scannerHome}/bin/sonar-scanner -Dsonar.projectKey=vprofile \
                            -Dsonar.projectName=vprofile-repo \
                            -Dsonar.projectVersion=1.0 \
                            -Dsonar.sources=src/ \
                            -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/ \
                            -Dsonar.junit.reportsPath=target/surefire-reports/ \
                            -Dsonar.jacoco.reportsPath=target/jacoco.exec \
                            -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml'''
                    }

                    timeout(time: 10, unit: 'MINUTES') {
                        waitForQualityGate abortPipeline: true
                    }
                }
            }
        }

        stage("Publish to Nexus Repository Manager") {
            steps {
                dir('v_project') {
                    script {
                        pom = readMavenPom file: "pom.xml";
                        filesByGlob = findFiles(glob: "target/*.${pom.packaging}");
                        echo "${filesByGlob[0].name} ${filesByGlob[0].path} ${filesByGlob[0].directory} ${filesByGlob[0].length} ${filesByGlob[0].lastModified}"
                        artifactPath = filesByGlob[0].path;
                        artifactExists = fileExists artifactPath;
                        if(artifactExists) {
                            // Generate timestamp: YYYYMMDD_HHMMSS
                            def timeStamp = sh(script: 'date +%Y%m%d_%H%M%S', returnStdout: true).trim();
                            def artVersion = "${env.BUILD_ID}-${timeStamp}";
                            echo "*** File: ${artifactPath}, group: ${pom.groupId}, packaging: ${pom.packaging}, version: ${artVersion}";
                            nexusArtifactUploader(
                                nexusVersion: NEXUS_VERSION,
                                protocol: NEXUS_PROTOCOL,
                                nexusUrl: NEXUS_URL,
                                groupId: pom.groupId,
                                version: artVersion,
                                repository: NEXUS_REPOSITORY,
                                credentialsId: NEXUS_CREDENTIAL_ID,
                                artifacts: [
                                    [artifactId: pom.artifactId,
                                    classifier: '',
                                    file: artifactPath,
                                    type: pom.packaging],
                                    [artifactId: pom.artifactId,
                                    classifier: '',
                                    file: "pom.xml",
                                    type: "pom"]
                                ]
                            );
                        } else {
                            error "*** File: ${artifactPath}, could not be found";
                        }
                    }
                }
            }
        }
    }
}
